#!/bin/bash

set -e

export VAULT_ADDR=http://127.0.0.1:8200
export VAULT_TOKEN=dev-only-token

n_arbitrary_secrets=${1:-45}

echo '{
	"roles": ["reader", "writer"],
	"token": "abc123",
	"url": "https://example.com"
}' |
    vault kv put -mount secret /user -
echo '{
  "client_id": "free",
  "client_secret": "palestine"
}' |
    vault kv put -mount secret /creds -
echo '{
  "user": "vim",
  "password": "actually-emacs",
  "pointer": "null"
}' |
    vault kv put -mount secret /azure/the -
echo '{
  "tenant-id": "oopa",
  "client-id": "gangnamn",
  "client-secret": "style"
}' |
    vault kv put -mount secret /yolo/swag -
echo '{
  "tenant-id": "oopa",
  "client-id": "gangnamn",
  "client-secret": "style"
}' |
    vault kv put -mount secret /if/you/can/read/the/full/path/of/this/key/you/are/the/person/in/the/red/flag/monitor/meme -
for i in $(seq 1 "$n_arbitrary_secrets"); do
    echo '{
  "tenant-id": "oopa",
  "client-id": "gangnamn",
  "client-secret": "style"
}' |
        vault kv put -mount secret /secret"$i" -
done
